### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by fodhelper** [thongtech/go-legacy-win7#1]
Hello

1. Other similar projects have more patches, are them necessary or not?
https://github.com/yangjuncode/debian-go-mingw-builder/tree/main/1.22/patch

2. Could you also add other Go versions? (1.21 & 1.22)

3. I know it's too far, some devs patched Golang to support Windows XP again! can you also give it a try?
Here is some info to patch Golang for Windows XP :
https://github.com/iDigitalFlame/XMT/issues/1

Thank you in advance

**Comment by thongtech** [comment]
Hi,

Thanks for reaching out!

Regarding the patches you mentioned, they are all covered in my project, except for:

- `00-apply_https___go_dev_cl_600296.patch`
  This is a cherry-picked patch from version 1.23 (since that one is 1.22), not directly related to Win7 support.
- `03-Revert__os__remove_5ms_sleep_on_Windows_in_Process_Wait_.patch`
  This doesn't seem to be directly related to Windows 7 compatibility, coz our program works fine without this patch.

As for adding Go versions 1.21/1.22 and supporting Windows XP, while these are interesting ideas, my current focus is to maintain compatibility with Windows Server 2008 R2 for my legacy web application on the latest stable version.

I appreciate your suggestions and would consider them if there's a future use case for it.

**Comment by thongtech** [comment]
> > 03-Revert__os__remove_5ms_sleep_on_Windows_in_Process_Wait_.patch
> > This doesn't seem to be directly related to Windows 7 compatibility, coz our program works fine without this patch.
> 
> It seems like this Patch is needed for Windows 8 and Windows Server 2012 [golang/go#57004 (comment)](https://github.com/golang/go/issues/57004#issuecomment-1634397530)

Good catch! This patch is indeed needed to prevent race conditions in `os.RemoveAll` on pre-Windows 10 systems as mentioned on the issue.

I've reimplemented the fix in commit [`cf3a4d4`](https://github.com/thongtech/go-legacy-win7/commit/cf3a4d4bb96092dcc87454133a9a77ea4454a60d) and updated the release accordingly.

Feel free to let me know if you spot any other patches that need attention.

Thank you and Merry Christmas 🎄
